- src/core/decrypt.ts
- src/core/encrypt.ts
> fix: resolve import error

- src/core/decrypt.ts
- src/core/encrypt.ts
- src/utils/stringUtils.ts
Changed the function usage of TextEncoder to Uint8Array from buffer.
> fix: update encoding function

- .github/workflows/tests.yml
- eslint.config.js
- package-lock.json
- package.json
- src/__tests__/core/encryption.test.ts
- src/__tests__/core/verify.test.ts
- src/__tests__/fixtures/fixtures.ts
- src/__tests__/open-attestation/sign.test.ts
- src/__tests__/open-attestation/verify.test.ts
- src/__tests__/open-attestation/wrap.test.ts
- src/__tests__/w3c/sign.test.ts
- src/__tests__/w3c/verify.test.ts
- src/core/fragments/document-integrity/w3cSignatureIntegrity.ts
- src/core/fragments/document-status/transferableRecords/transferableRecordVerifier.ts
- src/core/fragments/document-status/transferableRecords/transferableRecordVerifier.types.ts
- src/core/fragments/document-status/transferableRecords/utils.ts
- src/core/fragments/document-status/w3cCredentialStatus.ts
- src/core/fragments/issuer-identity/w3cIssuerIdentity.ts
- src/core/verify.ts
- src/open-attestation/index.ts
- src/open-attestation/sign.ts
- src/open-attestation/types.ts
- src/open-attestation/utils.ts
- src/open-attestation/verify.ts
- src/open-attestation/wrap.ts
Remove OA packages and use TT packages.
> fix: swap oa lib with tt lib

- package-lock.json
- package.json
- src/verify/fragments/index.ts
- Fix incorrect export for TRANSFERABLE_RECORDS_TYPE
- version bump for package update
> fix: exports and package upgrade

- package-lock.json
- package.json
> fix: upgrade package

- src/__tests__/core/verify.test.ts
- src/verify/fragments/document-status/w3cEmptyCredentialStatus/index.ts
- src/verify/fragments/index.ts
- src/verify/verify.ts
- Enable credentialStatus verification for empty scenario
> feat: add w3cEmptyCredentialStatus fragment

- src/verify/fragments/document-status/w3cEmptyCredentialStatus/index.ts
> fix: import error

- package-lock.json
- package.json
- Upgrade token registry v4 package
> fix: upgrade pkgs

- .github/workflows/publish.yml
- package-lock.json
- package.json
- src/__tests__/fixtures/fixtures.ts
- src/__tests__/utils/documents/index.test.ts
- src/utils/documents/index.ts
- src/utils/index.ts
- Upgrade tradetrust-utils pkg
- Migrated function from tt-website
> fix: upgrade pkgs and migration function from website

- package-lock.json
- package.json
> fix: upgrade packages

- package-lock.json
- package.json
- src/core/endorsement-chain/fetchEscrowTransfer.ts
- src/core/endorsement-chain/helpers.ts
- src/core/endorsement-chain/retrieveEndorsementChain.ts
- src/core/endorsement-chain/useEndorsementChain.ts
- src/dnsprove/index.ts
- src/token-registry-v4/contracts.ts
- src/token-registry-v4/index.ts
- src/token-registry-v5/contracts.ts
- src/token-registry-v5/index.ts
- src/token-registry-v5/typedContractMethod.ts
- src/verify/fragments/document-status/transferableRecords/utils.ts
- src/verify/fragments/issuer-identity/w3cIssuerIdentity.ts
- tsconfig.json
- test resolution in alpha branch
> fix: ethers errors

- package.json
- src/core/endorsement-chain/fetchEscrowTransfer.ts
- src/verify/fragments/issuer-identity/w3cIssuerIdentity.ts
> fix: imports

- .gitignore
- eslint.config.js
- package-lock.json
- package.json
- src/__tests__/core/endorsement-chain.test.ts
- src/core/decrypt.ts
- src/core/encrypt.ts
- src/core/endorsement-chain/fetchEscrowTransfer.ts
- src/core/endorsement-chain/fetchTokenTransfer.ts
- src/core/endorsement-chain/helpers.ts
- src/core/endorsement-chain/retrieveEndorsementChain.ts
- src/core/endorsement-chain/useEndorsementChain.ts
- src/core/verify.ts
- src/dnsprove/index.ts
- src/open-attestation/sign.ts
- src/open-attestation/verify.ts
- src/open-attestation/wrap.ts
- src/token-registry-v4/contracts.ts
- src/token-registry-v4/index.ts
- src/token-registry-v5/contracts.ts
- src/token-registry-v5/index.ts
- src/token-registry-v5/typedContractMethod.ts
- src/utils/ethers/index.ts
- src/utils/stringUtils/index.ts
- src/verify/fragments/document-status/transferableRecords/utils.ts
- src/verify/fragments/issuer-identity/w3cIssuerIdentity.ts
- src/w3c/sign.ts
- src/w3c/verify.ts
- tsconfig.json
- vitest.config.ts
- add ethers v6 support for endorsement chain
- streamlined code for endorsement chain
> fix: ethers error

- package.json
> fix: package

- package-lock.json
- package.json
- updated @tradetrust-tt/tradetrust-utils to 2.2.0
> fix: update tradetrust utils

- src/core/endorsement-chain/useEndorsementChain.ts
- add new getDocumentOwner function
> fix: add getDocumentOwner

- package-lock.json
- package.json
- src/__tests__/core/verify.test.ts
- src/core/verify.ts
- src/verify/fragments/document-integrity/w3cSignatureIntegrity.ts
- src/verify/fragments/document-status/w3cCredentialStatus.ts
- src/verify/fragments/document-status/w3cEmptyCredentialStatus/index.ts
- src/w3c/verify.ts
- Add documentLoader option to verifyDocument function
> fix: allow getDocumentLoader for verifyDocument

- src/utils/gasStation/index.ts
- src/utils/index.ts
> fix: export gas station function from tt utils

- src/utils/gasStation/index.ts
- src/utils/index.ts
> fix: version bump

- src/token-registry-functions/mint.ts
> fix: trigger release

- CHANGELOG.md
- package-lock.json
- package.json
- src/core/documentBuilder.ts
- src/utils/errorMessages/index.ts
- src/utils/errorMessages/types.ts
Rebase v1 alpha branch with main
> chore: rebase v1 with main
